# Generated by Django 4.0.10 on 2023-08-03 11:52

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Scan",
            fields=[
                (
                    "hash",
                    models.CharField(
                        editable=False,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="The hash of the scan.",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Date and time the scan was created.",
                    ),
                ),
                ("raw_data", models.TextField(verbose_name="The original scan data.")),
                (
                    "processed_data",
                    models.JSONField(
                        default=dict, verbose_name="The processed scan data."
                    ),
                ),
            ],
            options={
                "verbose_name": "scan",
                "verbose_name_plural": "scans",
                "default_permissions": (),
            },
        ),
    ]
