# Generated by Django 4.0.10 on 2023-08-12 19:27

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aa_intel_tool", "0004_alter_scandata_section"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scan",
            options={
                "default_permissions": (),
                "verbose_name": "Scan",
                "verbose_name_plural": "Scans",
            },
        ),
        migrations.AlterModelOptions(
            name="scandata",
            options={
                "default_permissions": (),
                "verbose_name": "Scan data",
                "verbose_name_plural": "Scan data",
            },
        ),
        migrations.AlterField(
            model_name="scan",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Creation date/time"
            ),
        ),
        migrations.AlterField(
            model_name="scan",
            name="hash",
            field=models.CharField(
                editable=False,
                max_length=30,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Scan hash",
            ),
        ),
        migrations.AlterField(
            model_name="scan",
            name="raw_data",
            field=models.TextField(verbose_name="Scan RAW data"),
        ),
        migrations.AlterField(
            model_name="scan",
            name="scan_type",
            field=models.CharField(
                choices=[
                    ("invalid", "Invalid scan data"),
                    ("dscan", "D-Scan"),
                    ("fleetcomp", "Fleet Composition"),
                    ("chatlist", "Chat List"),
                ],
                default="invalid",
                max_length=9,
                verbose_name="Scan type",
            ),
        ),
        migrations.AlterField(
            model_name="scandata",
            name="processed_data",
            field=models.JSONField(default=dict, verbose_name="Processed scan data"),
        ),
        migrations.AlterField(
            model_name="scandata",
            name="section",
            field=models.CharField(
                choices=[
                    ("invalid", "Invalid scan data"),
                    ("pilotlist", "Pilot list"),
                    ("corporationlist", "Corporation list"),
                    ("alliancelist", "Alliance list"),
                    ("shiptypes", "Ship types"),
                    ("shiplist", "Ship list"),
                    ("shiplist_on_grid", "Ship list (on grid)"),
                    ("shiplist_off_grid", "Ship list (off grid)"),
                    ("structures_on_grid", "Structures (on grid)"),
                    ("deployables_on_grid", "Deployables (on grid)"),
                ],
                default="invalid",
                max_length=19,
                verbose_name="Scan section",
            ),
        ),
    ]
