# Generated by Django 4.0.10 on 2023-08-23 12:13

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aa_intel_tool", "0006_alter_scandata_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scandata",
            name="section",
            field=models.CharField(
                choices=[
                    ("invalid", "Invalid scan data"),
                    ("pilotlist", "Pilot list"),
                    ("corporationlist", "Corporation list"),
                    ("alliancelist", "Alliance list"),
                    ("shiptypes", "Ship types"),
                    ("shiplist", "Ship list"),
                    ("shiplist_on_grid", "Ship list (on grid)"),
                    ("shiplist_off_grid", "Ship list (off grid)"),
                    ("structures_on_grid", "Structures (on grid)"),
                    ("starbases_on_grid", "Starbases (on grid)"),
                    ("deployables_on_grid", "Deployables (on grid)"),
                    ("miscellaneous_on_grid", "Miscellaneous (on grid)"),
                    ("solar_system_information", "System information"),
                ],
                default="invalid",
                max_length=24,
                verbose_name="Scan section",
            ),
        ),
    ]
