# Generated by Django 4.0.10 on 2023-08-28 13:27

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aa_intel_tool", "0008_alter_scandata_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scan",
            name="scan_type",
            field=models.CharField(
                choices=[
                    ("invalid", "Invalid scan data"),
                    ("dscan", "D-Scan"),
                    ("fleetcomp", "Fleet Composition"),
                    ("chatlist", "Chat list"),
                ],
                default="invalid",
                max_length=9,
                verbose_name="Scan type",
            ),
        ),
    ]
